export enum LookupDiscriminator {
  PRIORITY = 'PRIORITY',
  CLASSIFICATION = 'CLASSIFICATION',
  ISSUE_LEVEL = 'ISSUE_LEVEL',
  ISSUE_TYPE = 'ISSUE_TYPE',
  ISSUE_STATUS = 'ISSUE_STATUS',
  VALIDITY_DEGREE_TYPE = 'VALIDITY_DEGREE_TYPE',
  VALIDITY_DEGREE = 'VALIDITY_DEGREE',
  EVENT_TYPE = 'EVENT_TYPE',
  DATE_TYPE = 'DATE_TYPE',
  DEFAULT_DATE_VALUE = 'DEFAULT_DATE_VALUE',
  INPUT_TYPE = 'INPUT_TYPE',
  DATA_TYPE = 'DATA_TYPE',
  ISSUE_LINK_TYPE = 'ISSUE_LINK_TYPE',
  STATE = 'STATE',
  CHANGE_TYPE = 'CHANGE_TYPE',
  FIELD_TYPE = 'FIELD_TYPE',
  SECTION = 'SECTION',
  RECURRENCE_TYPE = 'RECURRENCE_TYPE',
  CALENDAR_TYPE = 'CALENDAR_TYPE',
  RECURRENCE_END_TYPE = 'RECURRENCE_END_TYPE',
  WEEKDAY = 'WEEKDAY',
  BUSINESS_TYPE = 'BUSINESS_TYPE',
  BULLETIN_TYPE = 'BULLETIN_TYPE',
  BULLETIN_STATE = 'BULLETIN_STATE',
  REFERRAL_TYPE = 'REFERRAL_TYPE',
  ASSIGNEE_APPROVAL_STATUS = 'ASSIGNEE_APPROVAL_STATUS',
  ASSIGNEE_ACTION_TYPE = 'ASSIGNEE_ACTION_TYPE',
  ATTACHMENT_TYPE = 'ATTACHMENT_TYPE',
  TOPIC_TYPE = 'TOPIC_TYPE',
  REFERRAL_RULE_TYPE = 'REFERRAL_RULE_TYPE',
  REVIEW_TEMPLATE = 'REVIEW_TEMPLATE',
  NAVIGATION_ORG = 'NAVIGATION_ORG',
  NOTIFICATION_LEVEL = 'NOTIFICATION_LEVEL',
  NOTIFICATION_TYPE = 'NOTIFICATION_TYPE',
  SCHEDULE_ACTION_PARENT = 'SCHEDULE_ACTION_PARENT',
  SCHEDULE_ACTION_TYPE = 'SCHEDULE_ACTION_TYPE',
  SCHEDULE_STATUS = 'SCHEDULE_STATUS',
  TRANSMISSION_STATUS = 'TRANSMISSION_STATUS',
  TRANSMISSION_ACTION = 'TRANSMISSION_ACTION',
  WORKSTATION_SEND_TYPE = 'WORKSTATION_SEND_TYPE',
  WORKSTATION_ACTIVITY_TYPE = 'WORKSTATION_ACTIVITY_TYPE',
  SETTING_TYPE = 'SETTING_TYPE',
  GROUP_TYPE = 'GROUP_TYPE',
  METRIC_NAME = 'METRIC_NAME',
  SYSTEM_VARIABLE = 'SYSTEM_VARIABLE',
  MAX_PUBLISH_DURATION = 'MAX_PUBLISH_DURATION',
  COMPARISON_OPERATOR = 'COMPARISON_OPERATOR',
  SCHEDULE_LINK_TYPE = 'SCHEDULE_LINK_TYPE',
}

export enum MaxPublishDuration {
  NONE = 'NONE',
  THREE_DAY = 'THREE_DAY',
  THREE_HOUR = 'THREE_HOUR',
  EIGHT_HOUR = 'EIGHT_HOUR',
  ONE_DAY = 'ONE_DAY',
  TWO_DAY = 'TWO_DAY',
  SEVEN_DAY = 'SEVEN_DAY',
  ONE_HOUR = 'ONE_HOUR',
  ONE_MIN = 'ONE_MIN',
}

export enum Priority {
  NORMAL = 'NORMAL',
  URGENT = 'URGENT',
  HIGH_URGENT = 'HIGH_URGENT',
  INSTANT = 'INSTANT',
}

export enum EventType {
  OCCASION = 'OCCASION',
  MEETING = 'MEETING',
  EVENT = 'EVENT',
}

export enum DefaultDateValue {
  TODAY = 'TODAY',
  ONE_DAY_AGO = 'ONE_DAY_AGO',
  ONE_DAY_LATER = 'ONE_DAY_LATER',
  TWO_DAY_AGO = 'TWO_DAY_AGO',
  TWO_DAY_LATER = 'TWO_DAY_LATER',
  ONE_HOUR_LATER = 'ONE_HOUR_LATER',
  ONE_HOUR_AGO = 'ONE_HOUR_AGO',
  TWO_HOUR_LATER = 'TWO_HOUR_LATER',
  TWO_HOUR_AGO = 'TWO_HOUR_AGO',
}

export enum InputType {
  TEXT = 'TEXT',
  SELECT = 'SELECT',
  MULTISELECT = 'MULTISELECT',
  TREE_SELECT_TOPIC = 'TREE_SELECT_TOPIC',
  TREE_SELECT_RESOURCE = 'TREE_SELECT_RESOURCE',
  POSITION_SELECT = 'POSITION_SELECT',
  ORG_SELECT = 'ORG_SELECT',
  GROUP_SELECT = 'GROUP_SELECT',
  CHECKBOX = 'CHECKBOX',
  RADIO = 'RADIO',
  TEXTAREA = 'TEXTAREA',
  DATE = 'DATE',
  DATETIME_LOCAL = 'DATETIME_LOCAL',
  TIME = 'TIME',
  CARD = 'CARD',
  STATISTICS = 'STATISTICS',
  CHECKBOX_GROUP = 'CHECKBOX_GROUP',
  COLOR_PICKER = 'COLOR_PICKER',
  SLIDER = 'SLIDER',
  RATE_PICKER = 'RATE_PICKER',
  MAP = 'MAP',
}

export enum DataType {
  STRING = 'STRING',
  NUMBER = 'NUMBER',
  FLOAT = 'FLOAT',
  BOOLEAN = 'BOOLEAN',
  DATE = 'DATE',
  TIME = 'TIME',
  DATETIME = 'DATETIME',
  TEXT = 'TEXT',
  SERIAL = 'SERIAL',
  GEOMETRY = 'GEOMETRY',
}

export enum IssueLinkType {
  RELATED = 'RELATED',
  FOLLOWING = 'FOLLOWING',
  BASE = 'BASE',
  AFTER = 'AFTER',
  RELATED_COMMAND = 'RELATED_COMMAND',
  FOLLOWING_COMMAND = 'FOLLOWING_COMMAND',
  BASE_COMMAND = 'BASE_COMMAND',
  AFTER_COMMAND = 'AFTER_COMMAND',
  FINISH_TO_START = 'FINISH_TO_START',
  START_TO_START = 'START_TO_START',
  FINISH_TO_FINISH = 'FINISH_TO_FINISH',
  START_TO_FINISH = 'START_TO_FINISH',
}

export enum State {
  DRAFT = 'DRAFT',
  REFERENCE = 'REFERENCE',
  CHECK = 'CHECK',
  CHECK2 = 'CHECK2',
  CHECK3 = 'CHECK3',
  ARCHIVE = 'ARCHIVE',
  PERSONAL_ARCHIVE = 'PERSONAL_ARCHIVE',
  DELETE = 'DELETE',
  DELETE2 = 'DELETE2',
  DELETE3 = 'DELETE3',
  EDIT = 'EDIT',
  EDIT2 = 'EDIT2',
  EDIT3 = 'EDIT3',
  COMMAND_ACTION = 'COMMAND_ACTION',
}

export enum ChangeType {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
}

export enum FieldType {
  ISSUE = 'ISSUE',
}

export enum RecurrenceType {
  DAILY = 'DAILY',
  WEEKLY = 'WEEKLY',
  MONTHLY = 'MONTHLY',
  YEARLY = 'YEARLY',
}

export enum CalendarType {
  GREGORIAN = 'GREGORIAN',
  SOLAR = 'SOLAR',
  LUNAR = 'LUNAR',
}

export enum RecurrenceEndType {
  END_DATE = 'END_DATE',
  OCCURRENCE_COUNT = 'OCCURRENCE_COUNT',
  NO_END = 'NO_END',
}

export enum Weekday {
  SUN = 'SUN',
  MON = 'MON',
  TUE = 'TUE',
  WED = 'WED',
  THU = 'THU',
  FRI = 'FRI',
  SAT = 'SAT',
}

export enum DaysOfWeek {
  SUN = 0,
  MON = 1,
  TUE = 2,
  WED = 3,
  THU = 4,
  FRI = 5,
  SAT = 6,
}

export enum BusinessType {
  KHABIR = 'KHABIR',
  DASTOOR = 'DASTOOR',
}

export enum SettingKey {
  STATIC_PROCESS_KEY = 'STATIC_PROCESS_KEY',
  AUTO_PROCESS_KEY = 'AUTO_PROCESS_KEY',
  COMMAND_STATIC_PROCESS_KEY = 'COMMAND_STATIC_PROCESS_KEY',
  COMMAND_AUTO_PROCESS_KEY = 'COMMAND_AUTO_PROCESS_KEY',
  WORK_SPACE_PROCESS_KEY = 'WORK_SPACE_PROCESS_KEY',
  WORK_SPACE_DRAW_KEY = 'WORK_SPACE_DRAW_KEY',
  DEFAULT_REPORT_ID = 'DEFAULT_REPORT_ID',
  DEFAULT_COMMAND_REPORT_ID = 'DEFAULT_COMMAND_REPORT_ID',
  MAX_CHARACTER_TITLE_KEY = 'MAX_CHARACTER_TITLE_KEY',
  MAX_CHARACTER_TEXT_KEY = 'MAX_CHARACTER_TEXT_KEY',
  MAX_CHARACTER_TAG_KEY = 'MAX_CHARACTER_TAG_KEY',
  MAX_CHARACTER_SUMMARY_KEY = 'MAX_CHARACTER_SUMMARY_KEY',
  MAX_CHARACTER_CONSIDERATIONS_KEY = 'MAX_CHARACTER_CONSIDERATIONS_KEY',
  MAX_CHARACTER_ATTACHMENT_DESCRIPTION_KEY = 'MAX_CHARACTER_ATTACHMENT_DESCRIPTION_KEY',
  STATIC_DELETE_PROCESS_KEY = 'STATIC_DELETE_PROCESS_KEY',
  AUTO_DELETE_PROCESS_KEY = 'AUTO_DELETE_PROCESS_KEY',
  STATIC_EDIT_PROCESS_KEY = 'STATIC_EDIT_PROCESS_KEY',
  AUTO_EDIT_PROCESS_KEY = 'AUTO_EDIT_PROCESS_KEY',
}

export enum ReferralType {
  ADD = 'ADD',
  RESTRICT = 'RESTRICT',
}

export enum Section {
  DRAFT = 'DRAFT',
  ARRIVED = 'ARRIVED',
  REFERENCES = 'REFERENCES',
  SEARCH = 'SEARCH',
  ARCHIVED = 'ARCHIVED',
  DELETED = 'DELETED',
  BULLETIN_MANAGEMENT = 'BULLETIN_MANAGEMENT',
  BULLETIN_CARTABLE = 'BULLETIN_CARTABLE',
  ARRIVED_ORDER = 'ARRIVED_ORDER',
  ISSUED_ORDER = 'ISSUED_ORDER',
  DRAFT_ORDER = 'DRAFT_ORDER',
  ARCHIVED_ORDER = 'ARCHIVED_ORDER',
  DELETED_ORDER = 'DELETED_ORDER',
  FOLLOW_UP_ORDER = 'FOLLOW_UP_ORDER',
  NEWS_DELEGATION = 'NEWS_DELEGATION',
  COMMAND_DELEGATION = 'COMMAND_DELEGATION',
  PROJECT = 'PROJECT',
  PROJECT_DETAILS = 'PROJECT_DETAILS',
  PROJECT_DRAFT = 'PROJECT_DRAFT',
  INTERNET_NEWS = 'INTERNET_NEWS',
  SEARCH_ORDER = 'SEARCH_ORDER',
}

export enum AssigneeApprovalStatus {
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  ROLLBACKED = 'ROLLBACKED',
}

export enum IssueStatus {
  TODO = 'TODO',
  DOING = 'DOING',
  DONE = 'DONE',
  CANCELED = 'CANCELED',
  STOPPED = 'STOPPED',
}

export enum IssueType {
  INTERNET_NEWS = 'INTERNET_NEWS',
  ORG_NEWS = 'ORG_NEWS',
}

export enum IssueTypeIssueAssigneeAction {
  MANEUVER = 'MANEUVER',
  OPERATION = 'OPERATION',
  VISIT = 'VISIT',
  MEETING = 'MEETING',
}

export enum FollowUpType {
  FIRST_FOLLOW_UP = 'FIRST_FOLLOW_UP',
  SECOND_FOLLOW_UP = 'SECOND_FOLLOW_UP',
  PHONE_FOLLOW_UP = 'PHONE_FOLLOW_UP',
}

export enum AttachmentType {
  FILE_ATTACHMENT = 'FILE_ATTACHMENT',
  VOICE = 'VOICE',
  FEATURING_IMAGE = 'FEATURING_IMAGE',
}

export enum TopicType {
  CUSTOMIZE = 'CUSTOMIZE',
  BASE = 'BASE',
}

export enum ReferralRuleType {
  REFERENCE = 'REFERENCE',
  RELEASE = 'RELEASE',
  REVIEW = 'REVIEW',
  DELETE = 'DELETE',
  EDIT = 'EDIT',
}

export enum ReviewTemplate {
  NONE = 'NONE',
  ONE_STEP = 'ONE_STEP',
  SERIES_TWO_STEP = 'SERIES_TWO_STEP',
  SERIES_THREE_STEP = 'SERIES_THREE_STEP',
  PARALLEL_TWO_STEP = 'PARALLEL_TWO_STEP',
  PARALLEL_THREE_STEP = 'PARALLEL_THREE_STEP',
  PARALLEL_TWO_STEP_DEPEND = 'PARALLEL_TWO_STEP_DEPEND',
  PARALLEL_THREE_STEP_DEPEND = 'PARALLEL_THREE_STEP_DEPEND',
  NO_CHECK = 'NO_CHECK',
}

export enum NavigationOrg {
  NONE = 'NONE',
  UP_TO = 'UP_TO',
  UP_TO_CHECK = 'UP_TO_CHECK',
  UP_TO_TWO = 'UP_TO_TWO',
  UP_TO_TWO_CHECK = 'UP_TO_TWO_CHECK',
  DOWN_TO = 'DOWN_TO',
  DOWN_TO_TWO = 'DOWN_TO_TWO',
  BESIDE = 'BESIDE',
  TO_ME = 'TO_ME',
  SUBSTITUTE = 'SUBSTITUTE',
  COMMANDER = 'COMMANDER',
  SECRETARIAT = 'SECRETARIAT',
}

export enum BulletinState {
  IN_QUEUE = 'IN_QUEUE',
  REPORT_CREATED = 'REPORT_CREATED',
  PUBLISHED = 'PUBLISHED',
}

export enum AssigneeActionType {
  ACTION_CREATE = 'ACTION_CREATE',
  ACTION_FOLLOW_UP = 'ACTION_FOLLOW_UP',
}

export enum NotificationType {
  VISUAL = 'VISUAL',
  AUDIO = 'AUDIO',
  TEXT = 'TEXT',
  SMS = 'SMS',
  MESSAGE = 'MESSAGE',
}

export enum NotificationLevel {
  NORMAL_MESSAGE = 'NORMAL_MESSAGE',
  IMPORTANT_MESSAGE = 'IMPORTANT_MESSAGE',
  IMPORTANT_ALERT = 'IMPORTANT_ALERT',
  SPECIAL_ALERT = 'SPECIAL_ALERT',
}

export enum ScheduleActionParent {
  SYSTEMATIC = 'SYSTEMATIC',
  ISSUE_WITH_CONDITIONS = 'ISSUE_WITH_CONDITIONS',
  ISSUE_NO_CONDITIONS = 'ISSUE_NO_CONDITIONS',
  ORDER_WITH_CONDITIONS = 'ORDER_WITH_CONDITIONS',
}

export enum ScheduleActionType {
  ISSUE_FORWARD = 'ISSUE_FORWARD',
  ISSUE_BACKWARD = 'ISSUE_BACKWARD',
  ISSUE_EDIT = 'ISSUE_EDIT',
  ISSUE_ARCHIVE = 'ISSUE_ARCHIVE',
  ISSUE_DELETE = 'ISSUE_DELETE',
  ORDER_FORWARD = 'ORDER_FORWARD',
  ORDER_EDIT = 'ORDER_EDIT',
  ORDER_ACTION_CREATE = 'ORDER_ACTION_CREATE',
  ORDER_ACTION_EDIT = 'ORDER_ACTION_EDIT',
  ORDER_DEPENDENCY = 'ORDER_DEPENDENCY',
  ISSUE_COUNT = 'ISSUE_COUNT',
  ORDER_COUNT = 'ORDER_COUNT',
  ORDER_FINAL_SCORE = 'ORDER_FINAL_SCORE',
  ORDER_OWNER_SCORE = 'ORDER_OWNER_SCORE',
  ORDER_SELF_SCORE = 'ORDER_SELF_SCORE',
  ORDER_REVIEWER_SCORE = 'ORDER_REVIEWER_SCORE',
  ORDER_SYSTEM_SCORE = 'ORDER_SYSTEM_SCORE',
  SENDER_FIRST_FOLLOW_UP = 'SENDER_FIRST_FOLLOW_UP',
  SENDER_SECOND_FOLLOW_UP = 'SENDER_SECOND_FOLLOW_UP',
  SENDER_PHONE_FOLLOW_UP = 'SENDER_PHONE_FOLLOW_UP',
  RECEIVER_FIRST_FOLLOW_UP = 'RECEIVER_FIRST_FOLLOW_UP',
  RECEIVER_SECOND_FOLLOW_UP = 'RECEIVER_SECOND_FOLLOW_UP',
  RECEIVER_PHONE_FOLLOW_UP = 'RECEIVER_PHONE_FOLLOW_UP',
  BULLETIN_PUBLISH = 'BULLETIN_PUBLISH',
  BULLETIN_NO_ISSUE = 'BULLETIN_NO_ISSUE',
  ISSUE_AUTO_REFERENCE = 'ISSUE_AUTO_REFERENCE',
  ISSUE_AUTO_RELEASE = 'ISSUE_AUTO_RELEASE',
  DISABLE_SUBSTITUTE_DELEGATOR = 'DISABLE_SUBSTITUTE_DELEGATOR',
  DISABLE_SUBSTITUTE_DELEGATED = 'DISABLE_SUBSTITUTE_DELEGATED',
}

export enum ScheduleStatus {
  NEW = 'NEW',
  RUNNING = 'RUNNING',
  DONE = 'DONE',
}

export enum TransmissionStatus {
  INITIALIZE = 'INITIALIZE',
  READY_TO_PROCESS = 'READY_TO_PROCESS',
  PROCESSED = 'PROCESSED',
  READY_TO_SEND = 'READY_TO_SEND',
  SENT = 'SENT',
  FAILED = 'FAILED',
}

export enum TransmissionAction {
  REF_ORG = 'REF_ORG',
  EDIT = 'EDIT',
  DELETE = 'DELETE',
  ACK = 'ACK',
  INTERNET_NEWS = 'INTERNET_NEWS',
  ORGANIZATIONAL_NEWS = 'ORGANIZATIONAL_NEWS',
  IMPORT = 'IMPORT',
}

export enum SettingType {
  BY_POSITION = 'BY_POSITION',
  BY_LOCAL_ADMIN = 'BY_LOCAL_ADMIN',
  BY_ADMIN = 'BY_ADMIN',
}

export enum GroupType {
  DEFAULT = 'DEFAULT',
  FAVORITE = 'FAVORITE',
  INTER_ORGANIZATIONAL = 'INTER_ORGANIZATIONAL',
}

export enum MetricName {
  BY_FOLLOW_UP = 'BY_FOLLOW_UP',
  BY_TIMEWORK = 'BY_TIMEWORK',
  BY_PROGRESS_PERCENTAGE = 'BY_PROGRESS_PERCENTAGE',
  BY_TIME_RATIO_SCORE = 'BY_TIME_RATIO_SCORE',
  BY_EVALUATION = 'BY_EVALUATION',
  BY_CREATIVITY = 'BY_CREATIVITY',
  BY_PRECISION = 'BY_PRECISION',
  BY_SPEED = 'BY_SPEED',
  BY_MANUALLY = 'BY_MANUALLY',
}

export enum DateType {
  OCCASION = 'OCCASION',
  RANGE = 'RANGE',
  EXACT = 'EXACT',
  APPROXIMATE = 'APPROXIMATE',
}

export enum WorkstationSendType {
  OFFLINE = 'OFFLINE',
  BY_API = 'BY_API',
  BY_FILE = 'BY_FILE',
  BY_DB = 'BY_DB',
  INTERNET_NEWS = 'INTERNET_NEWS',
  ORGANIZATIONAL_NEWS = 'ORGANIZATIONAL_NEWS',
}

export enum SystemVariable {
  FROM_POSITION = 'FROM_POSITION',
  FROM_USER = 'FROM_USER',
  TO_POSITION = 'TO_POSITION',
  TO_USER = 'TO_USER',
  CURRENT_DATETIME = 'CURRENT_DATETIME',
  KEY = 'KEY',
  BUSINESS_TYPE = 'BUSINESS_TYPE',
  ASSIGNEE_TYPE = 'ASSIGNEE_TYPE',
  ISSUE_TYPE = 'ISSUE_TYPE',
  ISSUE_STATUS = 'ISSUE_STATUS',
  ISSUE_DATE = 'ISSUE_DATE',
  ISSUE_TITLE = 'ISSUE_TITLE',
  ISSUE_DESCRIPTION = 'ISSUE_DESCRIPTION',
  ISSUE_CONFIRMED_DATE = 'ISSUE_CONFIRMED_DATE',
  ISSUE_PUBLISHED_DATE = 'ISSUE_PUBLISHED_DATE',
  ISSUE_LINK = 'ISSUE_LINK',
  ISSUE_COMPARISON_RESULT = 'ISSUE_COMPARISON_RESULT',
}

export enum ScheduleLinkType {
  TYPE = 'TYPE',
}
